export {
  MAP_SCHEMA_VERSION,
  MapDocumentSchema,
  MapElementSchema,
  MapBindingSchema,
  type MapDocument,
  type MapJoin,
  type ModulePlacement,
  type ModuleUse,
  type MapElement,
  type Layer,
  type TrackPathElement,
  type BerthElement,
  type SignalElement,
  type PlatformElement,
  type PlatformNumberElement,
  type StationElement,
  type LabelElement,
  type LevelCrossingElement,
  type SwitchedDiamondElement,
  type BufferStopElement,
  type RouteElement,
  type NeutralSectionElement,
  type TunnelElement,
  type ViaductElement,
  type WaterElement,
  type BoundaryElement,
  type MapBinding,
  type TdBerthBinding,
  type TdSBitBinding,
  type TdSBitBarrierBinding,
  type TdSBitBarrierInferredBinding,
  type TdSBitRouteBinding,
  type InferredBarrierInputDoc,
  type TopologyNode,
  type TopologyEdge,
} from "./document.js";
export {
  routeWarnings,
  validateMapDocument,
  type ValidationIssue,
  type ValidationResult,
} from "./validate.js";
export {
  DEFAULT_JOIN_TOLERANCE,
  nearestPositionOnTrack,
  routePointsOffTrack,
  snapToTrack,
  traceRoute,
  type GraphPoint,
  type TracedRoute,
  type TrackLike,
  type TrackPosition,
} from "./trackGraph.js";
export {
  canonicalSAddress,
  compileMapDocument,
  computeBoundingBox,
  sortElementsForPaint,
  weldTrackPaths,
  Z_INDEX_LAYER_BAND,
  type CompiledMapBundle,
} from "./compiler.js";
export { MAP_STYLE, MAP_CSS_TOKENS } from "./style.js";
export {
  applySignalNamePrefix,
  berthBoxes,
  defaultSideFor,
  defaultSignalDirection,
  signalColor,
  signalLabelPosition,
  signalPostGeometry,
  SIGNAL_BERTH_SEARCH,
  type SignalDirectionDecision,
  type SignalDisplayState,
  type SignalHead,
  type SignalPostGeometry,
  type SignalType,
} from "./signalGeometry.js";
export {
  berthRenderRect,
  levelCrossingGeometry,
  realisticLevelCrossingGeometry,
  neutralSectionGeometry,
  platformNumberGeometry,
  placedLabelAnchor,
  pointOnPathAtX,
  pointsBounds,
  scaleShapeWidth,
  findTrackCrossing,
  switchedDiamondGeometry,
  viaductWidth,
  type BarrierDisplayState,
  type SwitchedDiamondCorner,
  type SwitchedDiamondGeometry,
  type TrackCrossing,
  type LevelCrossingGeometry,
  type RealisticBarrierGeometry,
  type RealisticLevelCrossingGeometry,
  type NeutralSectionGeometry,
  type PlatformNumberGeometry,
  type PlacedLabel,
  type PlacedLabelFields,
  type Rect,
} from "./geometry.js";
export {
  bufferStopBounds,
  bufferStopDrawing,
  stopBoardParts,
  type DrawPrimitive,
  type PlacedDrawing,
} from "./drawing.js";
export { hiddenTracks, visibleRouteRuns } from "./hiddenTrack.js";
export {
  extractModule,
  flattenAssembledMap,
  fitJoin,
  isAssembledMap,
  joinTrackEnds,
  moduleSlugs,
  qualifyId,
  resolvePlacements,
  JOIN_MATCH_TOLERANCE,
  JOIN_TRACK_END_TOLERANCE,
  type ExtractResult,
  type FlattenResult,
  type JoinFit,
  type ModuleIssue,
  type ResolvedPlacement,
} from "./modules.js";
