export {
  MAP_SCHEMA_VERSION,
  MapDocumentSchema,
  MapElementSchema,
  MapBindingSchema,
  type MapDocument,
  type MapElement,
  type Layer,
  type TrackPathElement,
  type BerthElement,
  type SignalElement,
  type PlatformElement,
  type PlatformNumberElement,
  type StationElement,
  type LabelElement,
  type LevelCrossingElement,
  type NeutralSectionElement,
  type TunnelElement,
  type ViaductElement,
  type WaterElement,
  type BoundaryElement,
  type MapBinding,
  type TdBerthBinding,
  type TdSBitBinding,
  type TdSBitBarrierBinding,
  type TdSBitBarrierInferredBinding,
  type InferredBarrierInputDoc,
  type TopologyNode,
  type TopologyEdge,
} from "./document.js";
export { validateMapDocument, type ValidationIssue, type ValidationResult } from "./validate.js";
export {
  canonicalSAddress,
  compileMapDocument,
  computeBoundingBox,
  sortElementsForPaint,
  weldTrackPaths,
  Z_INDEX_LAYER_BAND,
  type CompiledMapBundle,
} from "./compiler.js";
export { MAP_STYLE, MAP_CSS_TOKENS } from "./style.js";
export {
  berthRenderRect,
  levelCrossingGeometry,
  realisticLevelCrossingGeometry,
  neutralSectionGeometry,
  placedLabelAnchor,
  pointOnPathAtX,
  pointsBounds,
  scaleShapeWidth,
  viaductWidth,
  type BarrierDisplayState,
  type LevelCrossingGeometry,
  type RealisticBarrierGeometry,
  type RealisticLevelCrossingGeometry,
  type NeutralSectionGeometry,
  type PlacedLabel,
  type PlacedLabelFields,
  type Rect,
} from "./geometry.js";
